package com.tourism.app.model.module;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Nov 28 09:46:12 EET 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleAMImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleAMImpl() {
    }

    /**
     * Container's getter for Country1.
     * @return Country1
     */
    public ViewObjectImpl getCountry1() {
        return (ViewObjectImpl)findViewObject("Country1");
    }

    /**
     * Container's getter for Invoice1.
     * @return Invoice1
     */
    public ViewObjectImpl getInvoice1() {
        return (ViewObjectImpl)findViewObject("Invoice1");
    }

    /**
     * Container's getter for Passengers1.
     * @return Passengers1
     */
    public ViewObjectImpl getPassengers1() {
        return (ViewObjectImpl)findViewObject("Passengers1");
    }

    /**
     * Container's getter for Reservation1.
     * @return Reservation1
     */
    public ViewObjectImpl getReservation1() {
        return (ViewObjectImpl)findViewObject("Reservation1");
    }

    /**
     * Container's getter for Trips1.
     * @return Trips1
     */
    public ViewObjectImpl getTrips1() {
        return (ViewObjectImpl)findViewObject("Trips1");
    }

    /**
     * Container's getter for Invoice2.
     * @return Invoice2
     */
    public ViewObjectImpl getInvoice2() {
        return (ViewObjectImpl)findViewObject("Invoice2");
    }

    /**
     * Container's getter for Passengers2.
     * @return Passengers2
     */
    public ViewObjectImpl getPassengers2() {
        return (ViewObjectImpl)findViewObject("Passengers2");
    }

    /**
     * Container's getter for Reservation2.
     * @return Reservation2
     */
    public ViewObjectImpl getReservation2() {
        return (ViewObjectImpl)findViewObject("Reservation2");
    }

    /**
     * Container's getter for Trips2.
     * @return Trips2
     */
    public ViewObjectImpl getTrips2() {
        return (ViewObjectImpl)findViewObject("Trips2");
    }

    /**
     * Container's getter for Passengers3.
     * @return Passengers3
     */
    public ViewObjectImpl getPassengers3() {
        return (ViewObjectImpl)findViewObject("Passengers3");
    }

    /**
     * Container's getter for InvoiceFk1VL1.
     * @return InvoiceFk1VL1
     */
    public ViewLinkImpl getInvoiceFk1VL1() {
        return (ViewLinkImpl)findViewLink("InvoiceFk1VL1");
    }

    /**
     * Container's getter for PassengersFk1VL1.
     * @return PassengersFk1VL1
     */
    public ViewLinkImpl getPassengersFk1VL1() {
        return (ViewLinkImpl)findViewLink("PassengersFk1VL1");
    }

    /**
     * Container's getter for ReservationFk1VL1.
     * @return ReservationFk1VL1
     */
    public ViewLinkImpl getReservationFk1VL1() {
        return (ViewLinkImpl)findViewLink("ReservationFk1VL1");
    }

    /**
     * Container's getter for TripsFk1VL1.
     * @return TripsFk1VL1
     */
    public ViewLinkImpl getTripsFk1VL1() {
        return (ViewLinkImpl)findViewLink("TripsFk1VL1");
    }

    /**
     * Container's getter for PassengersFk1VL2.
     * @return PassengersFk1VL2
     */
    public ViewLinkImpl getPassengersFk1VL2() {
        return (ViewLinkImpl)findViewLink("PassengersFk1VL2");
    }


    /**
     * Container's getter for ResPassengersLov1.
     * @return ResPassengersLov1
     */
    public ViewObjectImpl getResPassengersLov1() {
        return (ViewObjectImpl)findViewObject("ResPassengersLov1");
    }

    /**
     * Container's getter for Invoice2_1.
     * @return Invoice2_1
     */
    public ViewObjectImpl getInvoice2_1() {
        return (ViewObjectImpl)findViewObject("Invoice2_1");
    }
}
